CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_SHOW_COLOR=n   # if i remove or configure this macro CONFIG_LOG_BACKEND_SHOW_COLOR=n then no colors will not show
                                  # To have colors in the logged messages just enable it i.e CONFIG_LOG_BACKEND_SHOW_COLOR=y 
CONFIG_LOG_MODE_MINIMAL=n      # This configuration macro enables logger messages to be printed out without time stamp
                               # To have time stamp in the log just enable it i.e. CONFIG_LOG_MODE_MINIMAL=y
CONFIG_MYFUNCTION=y
