#CONFIG_GPIO=y                 "Already enabled in defconfig file"
CONFIG_LOG=y
#CONFIG_SERIAL=y               "Already enabled in defconfig file"
CONFIG_UART_ASYNC_API=y
CONFIG_UART_FUNC=y
CONFIG_LED_FUNC=y
