#I/O CONIFG SYSMBOLS
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_UART_ASYNC_API=y

#DEBUG UTILITIES
CONFIG_LOG=y

#Enabling Floating Point Support
CONFIG_FPU=y


#Enabling C++ Support
CONFIG_CPP=y

#ENABLING LIBC++ SUPPORT AS Zephyr does not include any C++ standard library implementation in source code form. 
CONFIG_GLIBCXX_LIBCPP=y
#ENABLING C++17 SUPPORT
CONFIG_STD_CPP17=y



