#CONFIG_GPIO=y                 "Already enabled in defconfig file"
CONFIG_LOG=y                   #Disabling Logger Module for prirotizing UART Threads.
CONFIG_TIMING_FUNCTIONS=y
#CONFIG_MAIN_THREAD_PRIORITY=0    #Setting Main Thread Priority to highest
#CONFIG_MAIN_STACK_SIZE=1048      #Increasing Main Stack Size to support C++ features

#CONFIG_SERIAL=y                "Already enabled in defconfig file"
CONFIG_UART_ASYNC_API=y
CONFIG_PRINTK=y
CONFIG_UART_FUNC=y
#CONFIG_TIMESLICING=y            # Enabling time slicing For same priority of threads
#CONFIG_TIMESLICE_SIZE=5000     # Each thread is allocated execution time of 1second, it is also defined in defconfig file
# CONFIG_TIMESLICE_PRIORITY=0 This value is set by default to 0
CONFIG_LED_FUNC=y

#Enabling C++ Support
CONFIG_CPP=y
#ENABLING LIBC++ SUPPORT AS Zephyr does not include any C++ standard library implementation in source code form. 
CONFIG_GLIBCXX_LIBCPP=y
#ENABLING C++17 SUPPORT
CONFIG_STD_CPP17=y
